# Generated by Django 4.0.5 on 2022-06-30 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDosFilmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('direcao', models.CharField(blank=True, max_length=55)),
                ('ano', models.CharField(max_length=25)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('resumo', models.TextField(blank=True)),
                ('genero', models.CharField(max_length=55)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lista.categoria')),
            ],
        ),
    ]
